In [33]:
import numpy as np 
import pandas as pd 
import matplotlib
from matplotlib import pyplot as plt 
from sklearn.linear_model import LinearRegression 

In [34]:
df = pd.DataFrame({
    "x" :[1,2,3],
    "y" : [1,3,4],
    "z" : [2 ,1 ,5]
})

In [35]:
df

x  y  z
0  1  1  2
1  2  3  1
2  3  4  5

In [36]:
class multiLR :

    def __init__(self):
        self.coef_ = None 
        self.intercept_ = None 
        
        
    def fit (self , X , y ):
        X = np.insert(X , 0 , 1 , axis = 1 )
        
        #β* = (X_transposeX)-¹X_transposey
        weights = np.linalg.inv((X.T@X))@(np.transpose(X))@y
        self.intercept_ = weights[0]
        self.coef_  = weights[1:]

    def predict(self, X):
        return np.dot(X,self.coef_) + self.intercept_
        
        
        

In [37]:
mullr = multiLR()

In [38]:
X = df.drop(columns=["z"])
y = df["z"]

In [39]:
mullr.fit(X,y)

In [40]:
mullr.coef_

array([ 9., -5.])

In [41]:
mullr.intercept_

np.float64(-2.0000000000002345)

In [42]:
mullr.predict(X)

array([2., 1., 5.])

In [43]:
import plotly.express as px
import plotly.graph_objects as go

In [44]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"

In [45]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model

Z_pred = mullr.predict(grid)
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()

In [46]:
lr = LinearRegression()

In [47]:
lr.fit(X,y)

LinearRegression()

In [48]:
lr.intercept_

np.float64(-1.9999999999999996)

In [49]:
lr.coef_

array([ 9., -5.])

In [50]:
# AS we see that coefficient and intercept are nearly similar 

In [51]:
# r2_score
lr.score(X,lr.predict(X))

1.0

In [52]:
from sklearn.datasets import make_regression
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [53]:
df = pd.DataFrame({'x':X[:,0],'y':X[:,1],'z':y})

In [54]:
df.head()

x         y          z
0 -0.359820 -0.507483 -42.057326
1 -0.794228 -1.176925 -10.796752
2  0.809026 -0.916662 -77.345296
3 -1.023068  1.933283  72.866590
4  0.166886 -0.030265  52.126326

In [55]:
df.shape

(100, 3)

In [56]:
X = df.drop("z" , axis = 1)
y = df["z"]

In [57]:
mlr = multiLR()

In [58]:
mlr.fit(X,y)

In [59]:
mlr.predict(X)

array([-2.69605007e+01, -6.34089546e+01, -4.38710384e+01,  9.75205042e+01,
       -1.65720048e-01,  4.44270706e+01,  1.24410088e+02,  1.27332983e+02,
        1.01045678e+02,  8.42618258e+00,  1.27954355e+01,  9.74509967e+01,
       -1.19271638e+02, -1.73821264e+01,  3.47120178e+01,  9.71160023e+01,
       -9.41269782e+00, -4.09003241e+01, -2.92133944e+01,  4.52233838e+01,
       -6.40065850e+01,  1.83351888e+02, -5.73771459e+01,  4.85250150e+01,
        3.89464311e+01, -7.72497739e+01,  2.42669561e+01, -7.36802618e+01,
        1.12655546e+01,  8.87592167e+01, -1.77981905e+01, -5.02391188e+00,
        4.20820829e+01, -5.95334591e+01, -5.87347668e+01,  4.00495970e+01,
       -6.40973399e+01,  9.72885408e+00, -3.11780040e+01,  4.76985479e+01,
        2.04717872e+01, -7.39020234e+01, -3.44822649e+01,  2.21765932e+01,
        9.52949610e+00, -9.71181386e-01,  7.77920841e+01, -4.78944051e+01,
        6.29271361e+00,  2.13484241e+00, -5.50517022e+01,  1.65769125e+02,
       -6.95503526e+00,  

In [60]:
mlr.coef_

array([ 3.74217256, 52.0176908 ])

In [61]:
mlr.intercept_

np.float64(0.7841051279566615)

In [62]:
mlr2 = LinearRegression()
mlr2.fit(X,y)

LinearRegression()

In [63]:
mlr.coef_ , mlr.intercept_

(array([ 3.74217256, 52.0176908 ]), np.float64(0.7841051279566615))

In [64]:
# hence both have similar results 


In [32]:
mlr2.predict([[-2.045881,0.8034048]])

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names



array([27.26612309])

In [65]:
fig = px.scatter_3d(df, x='x', y='y', z='z')
f1_range = np.linspace(df['x'].min(), df['x'].max(), 30)
f2_range = np.linspace(df['y'].min(), df['y'].max(), 30)

F1, F2 = np.meshgrid(f1_range, f2_range)

# Flatten grid for prediction
grid = np.c_[F1.ravel(), F2.ravel()]

# ---------------------------
# 3) Predict Z values using your model

Z_pred = mlr.predict(grid)
Z_pred = Z_pred.reshape(F1.shape)

# ---------------------------
# 4) Add prediction plane to scatter plot
# ---------------------------
fig.add_trace(
    go.Surface(
        x=F1,
        y=F2,
        z=Z_pred,
        colorscale="Viridis",
        opacity=0.5,
        showscale=False
    )
)

fig.update_layout(
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Prediction"
    )
)

fig.show()